### ISSUE TITLE
problems with move-assignment

### ISSUE THREAD

**Issue by bevel-lemelisk** [isapego/shared-resource#1]
Read your post in habrahabr. You have some problems in move assignment operator, i think. You should add check for self-assignment and release old mutex stored in m_shared_resource(if it isn't nullptr), before assign a new one to it

**Comment by bevel-lemelisk** [comment]
Or may be just delete this operator, cause without any non-copy public constructor it's not very useful

**Comment by bevel-lemelisk** [comment]
and you also forgot to add "return (*this);"

**Comment by isapego** [comment]
Thank you a lot for your help. I will fix it right away. Although, I did not released mutex on purpose - if you release it before move you'd get data race.

**Comment by bevel-lemelisk** [comment]
Don't understand how it result a race. You release old mutex(same behavior as in object destructor), then reassign a pointer to a new value. Can u explain?

**Comment by isapego** [comment]
Sure. First of all, mutex is always should be in a locked state while SharedResource<T>::Accessor is valid, because it unlocks mutex on destruction. So the left-hand accessor should get the mutex in the locked state. If we will unlock mutex, then move it, then lock it again that will lead to a possible race at the moment, when mutex is not locked. Not to mention the overhead for the unnecessary lock/unlock operations.

**Comment by isapego** [comment]
Maybe it will be clearer this way: we still have access to the resource after the assignment (by the second accessor) so we should keep the mutex locked.

**Comment by bevel-lemelisk** [comment]
Then you don't understand what i'm talking about. Your code of move assignment should be something like this:
Accessor& operator=(Accessor&& a)
{
  if (this != &a) {
    if (m_shared_resource != nullptr)
       m_shared_resource->m_mutex.unlock(); // Release OLD shared resource's mutex
    m_shared_resource = a.m_shared_resource;
    a.m_shared_resource = nullptr;
  }  
}

if u don't do this unlock, when u do something like this:
auto a1 = first_shared_resource.lock();
auto a2 = second_shared_resource.lock();
a1 = std::move(a2);

u will never execute unlock for first_shared_resource mutex, cause a1 destructor unlock second_shared_resource and a2 destructor does nothing

**Comment by bevel-lemelisk** [comment]
github ate my intendation( I'll add an debug output for your code, "Lock" where u perform mutex lock, "Unlock" where u perform unlock. See http://ideone.com/94Q24J it'll print 2 "Lock" but only 1 "Unlock"

**Comment by isapego** [comment]
Oh, now I see. You are 100% right of course. Thank you :+1:

**Comment by bevel-lemelisk** [comment]
I propose u to remove this operator(make it delete), because i can't see how u can use it good without any public non-copy constructor

**Comment by isapego** [comment]
Thank you a lot for your help. I decided to let it be. Could you please tell me your username at Habrahabr, so I could mention your name in the article?
